name: basic
env:
    COMMIT_MSG: ${{ github.event.head_commit.message }}
on: 
  push: # Startet den Workflow bei jedem Push in das Repository
  workflow_dispatch: # ERMÖGLICHT DEN MANUELLEN START
jobs:
  log:
    runs-on: ubuntu-latest # Nutzt einen virtuellen Ubuntu-Server von GitHub
    steps:
     - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
     - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
     - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
     - run: echo "Die Commit-Nachricht lautet:$COMMIT_MSG"
